### PR TITLE
Update 02.main-text.md

### PR DESCRIPTION
**Pull request by drviveksharma**
wanted to see if the program picks up a duplicate citation if the second author uses a different persistent identifier for a reference cited already is used but the second author.

### CODE REVIEW

**Review by dhimmel — APPROVED** [review]
thanks for trying this out.

I know the answer to your question, but will let you see for yourself.

**Comment by drviveksharma** [comment]
It is an amazing initiative. I guess it would require some mechanism to
check for duplicates before admitting a new citation like a gatekeeper
query to make sure the new bibtex entry does not have the same DOI as
something already in the bibtex file, if it does, it should prompt the
author to use the bibtex key after verification.
I am sure your clever team will come up with a solution.
Once again I congratulate you on your achievements thus far and wish this
gets more traction. I would love to continue testing as an enthusiastic
user.

Best regards
Vivek

**Comment by dhimmel** [comment]
Yeah currently Manubot will detect and consolidate some types of duplicate citations like `@doi:10.1097/MOT.0000000000000306` and `@doi:10.1097/mot.0000000000000306` and `@doi:10/f8mswg`. But we haven't generalized this to work across different sources (e.g. DOIs and PubMed).

**Comment by drviveksharma** [comment]
Still very commendable work. I am a luddite so zero coding skills will try
to restrict to using bibtex keys or another workaround to use jabref to
detect duplicates to clean database and then substitute persistent
identifiers by bibtex keys.🙂

**Comment by agitter** [comment]
I made an issue so we can continue discussing detecting duplicate citations more broadly: https://github.com/manubot/manubot/issues/253

In practice, we haven't had too many duplicate citations in collaborative manuscripts.  Using persistent identifiers in the order listed in https://github.com/manubot/rootstock/blob/master/USAGE.md#citations helps considerably.  In short, if there is a DOI, cite by DOI.

Manubot will work if you manage your references externally, but you'll lose the convenience of citation by identifier.  Ultimately the best usage for your needs is up to you.

**Comment by drviveksharma** [comment]
Thank you
With multi authored manuscripts it is pretty easy to get duplicate
references as there is no mechanism to sequentially see if the reference
already exists in the bib file, maybe I am missing something in the
workflow.?
Vivek

**Comment by agitter** [comment]
Manubot's approach of citation by identifier doesn't require a bib file.  Our strategy for avoiding duplicates in multi-author manuscripts is to use reference identifiers directly in the text and automatically extract the metadata.  For instance, in the citation you added here, `doi:10.1097/MOT.0000000000000306`, you did not have to create a bib file entry for that article.  Manubot uses the DOI to automatically retrieve the citation information.

Some users do prefer to manually track references in a bib file or use a bib file to provide metadata for references without good support for automatic citation information extraction.  Manubot supports those use cases.  However, if you want to manually use a bib file, you currently will have to watch for duplicates yourself.

**Comment by drviveksharma** [comment]
Sure, until manubot gets better at detecting duplicates across DOI, PMID
etc.
It is a very good writing resource and it's stellar features are
multiauthorship, citation by persistent identifiers and ability to use csl
for bibliography.
I am still learning how to get nice tables/ figures and crossreferences.
It is a very good resource and many thanks for making it available to
everyone.
Best regards
Vivek

**Pull request merged**
