### PR TITLE
Demonstrate manual references with BibTex

### PR DESCRIPTION
**Pull request by agitter**
Following up on https://github.com/manubot/manubot/pull/104#pullrequestreview-238865237.  I have not yet tested a local build.  I created the `.bib` file via export from Zotero.

_Edit: we can wait to merge this until after pulling in https://github.com/manubot/rootstock/pull/227 with the updated `manubot process` command_

### CODE REVIEW

**Comment by dhimmel** [comment]
I updated Manubot for this repo in https://github.com/manubot/try-manubot/commit/5d3dbf4617f286a5a7e4589edbad06d0d396dffb. Will rerun CI so we test with new manual reference support. See https://travis-ci.com/manubot/try-manubot/jobs/205471010

**Review by dhimmel — APPROVED** [review]
Will merge and let's see whether this works!

**Comment by dhimmel** [comment]
Output as intended at https://manubot.github.io/try-manubot/v/d6e0b9667480a754bb0924fa0a10b9abe4ca01d9/#ref-1Pz4wmGn

**Comment by agitter** [comment]
This new functionality is really great.  It makes working with manual references significantly easier.

**Pull request merged**
