### PR TITLE
Update manuscript title

### PR DESCRIPTION
**Pull request by agitter**
I'd like a more descriptive title for the Manubot catalog.  I'm open to other suggestions.

### CODE REVIEW

**Comment by dhimmel** [comment]
> Try Manubot: a demo manuscript for collaborative writing

Looks good to me. @vincerubinetti do you have opinions

**Comment by vincerubinetti** [comment]
`Try Manubot: A sandbox manuscript for anyone to practice contributing to`

Somehow it needs to be simply worded and clear what `try-manubot` actually is. People can practice with `rootstock`, so what makes this different is that it's a single one that many people (we're hoping) will contribute to and sort of graffiti.

As a side note, we should get it started with more sloppiness, so people don't feel hesitant to contribute because they're not sure what to write or put in there. Unless you do want to make it about a specific topic.

**Comment by dhimmel** [comment]
How about:

> Try Manubot: practice contributing to a demo manuscript

**Comment by agitter** [comment]
Of the two new options, I like the shorter
>Try Manubot: practice contributing to a demo manuscript

I would also encourage graffiti and sloppiness for this manuscript.

**Comment by vincerubinetti** [comment]
> Practice contributing to a demo manuscript

With this phrasing, it's not necessarily clear that the paper itself is the practice ground. It could be a paper that is a tutorial on how to contribute to a Manubot manuscript. Or it could be a paper espousing the benefits of using Manubot.

It should be clear that the paper itself is a sandbox.

From the `usage.md` pr:
```
Try editing the [demo manuscript](https://github.com/manubot/try-manubot) to quickly test Manubot formatting and citations.
```

To be most clear, it should be something like "Edit me to practice contributing to a collaborative Manubot paper" or "Manubot graffiti-script: This paper is a sandbox that anyone can practice contributing to". Something that makes the self-reference clear.

**Comment by agitter** [comment]
> Edit me to practice contributing to a collaborative Manubot paper

works for me.  This title won't appear many places besides the catalog and manuscript itself.  In both cases, make the invitation to edit seems useful.  @dhimmel are you okay with this title?

**Comment by dhimmel** [comment]
> Edit me to practice contributing to a collaborative Manubot paper

Good with me. Do we want "Manubot paper" or "Manubot manuscript"?

**Comment by agitter** [comment]
@dhimmel I'll switch to "manuscript" to keep with the "Manuscripts, open and automated" branding.

**Review by dhimmel — APPROVED** [review]

**Pull request merged**
